---
name: Matthew
surname: Hamilton
position: "Health Economist"
address: "Orygen"
phone: +61 413 976 905
profilepic: mhhs3.jpg
email: "matthew.hamilton@orygen.org.au"
github: matthewphamilton
linkedin: matthewhamiltonprofile
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Masters of Science - Health Economics", "2013", "National University of Ireland Galway", "Galway, Ireland",
  "Bachelor of Business Studies - Accounting & Finance with French", "1997", "University of Limerick", "Limerick, Ireland",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)

```

