---
title: "User_Params_For_PR_Pubs"
author: "Matthew Hamilton"
date: "04/03/2021"
output: html_document
---

```{r include=F}
sanitise_peer_revd_tb <- function(peer_revd_tb_spine){ 
  peer_revd_tb_spine <- peer_revd_tb_spine  %>%
  dplyr::mutate(Journal = Journal %>% purrr::map_chr(~ ifelse(.x == "Health Technology Assessment (Winchester, England)","Health Technology Assessment",.x))) %>%
  dplyr::mutate(Author = purrr::map_chr(Author, ~ stringr::str_replace_all(.x,"RICKWOOD","Rickwood")),
                Year = purrr::map_dbl(Year,~ifelse(is.na(.x),2021,.x))) %>%
  dplyr::arrange(dplyr::desc(Year)) 
  return(peer_revd_tb_spine)
}
```

```{r include=F}
scholar_id_1L_chr = "t1ZHrCoAAAAJ"
exclude_ids_chr = c("SeFeTyx0c_EC","NaGl4SEjCO4C","70eg2SAEIzsC","vV6vV6tmYwMC","pqnbT2bcN3wC","g5m5HwL7SMYC","M05iB0D1s5AC","ldfaerwXgEUC","lSLTfruPkqcC","J_g5lzvAfSwC","ns9cj8rnVeAC","HoB7MX3m0LUC","35N4QoGY0k4C","O3NaXMp0MMsC","2P1L_qKh6hAC", "RYcK_YlVTxYC", "RGFaLdJalmkC","GnPB-g6toBAC",
                    "IjCSPb-OGe4C","hMod-77fHWUC",
                    "0EnyYjriUFMC","7PzlFSSx8tAC",
                    "kNdYIx-mwKoC","r0BpntZqJG4C",
                    "KlAtU1dfN6UC",
                    "3fE2CSJIrl8C",
                    "5nxA0vEk-isC",
                    "2osOgNQ5qMEC",
                    "Y0pCki6q_DkC",
                    "qxL8FJ1GzNcC",
                    "Tyk-4Ss8FVUC",
                    "4DMP91E08xMC",
                    "9ZlFYXVOiuMC",
                    "L8Ckcad2t8MC",
                    "IWHjjKOFINEC", # Put back in when there is a title
                    "bEWYMUwI8FkC",
                    "blknAaTinKkC",
                    "k_IJM867U9cC",
                    "hC7cP41nSMkC",
                    "-f6ydRqryjwC",
                    "hFOr9nPyWt4C",
                    "mB3voiENLucC",
                    "HDshCWvjkbEC",
                    "TQgYirikUcIC",
                    "R3hNpaxXUhUC",
                    "e5wmG9Sq2KIC",
                    "RHpTSmoSYBkC",
                    "4JMBOYKVnBMC",
                    "j3f4tGmQtD8C",
                    "_Qo2XoVZTnwC",
                    "dhFuZR0502QC",
                    "BqipwSGYUEgC"
                    ) %>% unique()
```