---
title: "CV_Body"
author: "Matthew Hamilton"
date: "03/08/2020"
output: html_document
---

# Qualifications
```{r child="Quals_Body.Rmd", echo=FALSE}
```  

# Employment and Appointments
```{r child="Jobs_Body.Rmd", echo=FALSE}
``` 

# Peer-reviewed publications
```{r child="PR_Pubs_Body.Rmd", echo=FALSE}
```

# Non-peer-reviewed publications
```{r child="Non_PR_Body.Rmd", echo=FALSE}
```

# Scientific Software
```{r child="Software_Body.Rmd", echo=FALSE}
```
<!-- ## Documentation -->
<!-- ```{r child="../USER_PARAMS_RMDs/USER_SOFTWARE_INTRO.Rmd", echo=FALSE} -->
<!-- ``` -->

<!-- ## R Code Libraries -->
<!-- # ```{r child="Libs_Body.Rmd", echo=FALSE} -->
<!-- # ``` -->

<!-- &nbsp; -->

<!-- ## Executables & User Interfaces -->

<!-- Programs (study design and analysis):  https://readyforwhatsnext.org/docs/analyses/find/ -->

<!-- Subroutines (reporting templates): https://readyforwhatsnext.org/docs/reporting/ -->

<!-- User-interfaces (interactivity): https://readyforwhatsnext.org/docs/decision-aids/ -->

\newpage

# Presentations
```{r child="Talks_Body.Rmd", echo=FALSE}
```

# Grants
```{r child="Grants_Body.Rmd", echo=FALSE}
```

\newpage

# Teaching
```{r child="Teaching_Body.Rmd", echo=FALSE}
```  





