---
title: "Libs_Body"
author: "Matthew Hamilton"
date: "01/03/2021"
output: html_document
---

```{r child="../USER_PARAMS_RMDs/USER_LIBS_PARAMS.Rmd", echo=FALSE}
```
```{r }
libs_tb <- tibble::tibble(Name = r_libs_chr, 
                          Language = "R") %>%
  dplyr::mutate(Description = purrr::map_chr(.$Name,
                                             ~ utils::packageDescription(.x, 
                                                                             fields = "Description")),
                Title = purrr::map_chr(.$Name,
                                        ~ packageDescription(.x, fields = "Title")
                                       ),
                Version = purrr::map_chr(.$Name,
                                        ~ ifelse(stringr::str_detect(citation(.x) %>% 
                                                                            toBibtex() %>% 
                                                                            purrr::pluck(2),"doi "),
                                                 paste0("https://doi.org/",
                                                 stringr::str_extract_all(citation(.x) %>% 
                                                                            toBibtex() %>% 
                                                                            purrr::pluck(2),
                                                                          "(?<=\\{)[^{}]+(?=\\})")[[1]]),
                                                 (packageDescription(.x, 
                                                                     fields = "URL") %>%
                                                    strsplit(","))[[1]][1]
                                                 )
                                        #packageDescription(.x, fields = "Version")
                                        ),
                Author = purrr::map_chr(.$Name,
                                        ~ get_fn_auts(.x)),
                Repository = purrr::map_chr(.$Name,
                                        ~ get_pkg_dmnt_url(.x)),
                Date = purrr::map_chr(.$Name,
                                      ~ packageDate(.x) %>% format.Date("%d %B %Y"))
) %>%
  dplyr::mutate(Imports = purrr::map_chr(.$Name,
                                          ~ utils::packageDescription(.x, 
                                                                      fields = "Imports")))

 


```
