---
title: "Libs_Render_V1"
author: "Matthew Hamilton"
date: "01/03/2021"
output: html_document
---

#### A prototype software framework for transparent, reusable and updatable health economic models

```{r softwarefw}
libs_tb %>% 
  dplyr::filter(c(rep(T,6),
                  rep(F,length(r_libs_chr)-6))) %>%
  dplyr::mutate(Name_title = paste0(Name,
                                        " - ",
                                        Title)) %>%
  vitae::detailed_entries(what = Author,
                          when = Date,
                          with = Name_title,
                          where = Version,
                          .protect = TRUE)
```  

&nbsp;

#### Modules of an open source economic model of youth mental health

```{r softwaremod}
libs_tb %>% 
  dplyr::filter(c(rep(F,6),
                  rep(T,length(r_libs_chr)-6))) %>%
  dplyr::mutate(Name_title = paste0(Name,
                                        " - ",
                                        Title)) %>%
  vitae::detailed_entries(what = Author,
                          when = Date,
                          with = Name_title,
                          where = Version,
                          .protect = TRUE)
```  