---
title: "Peer Reviewed Publications"
author: "Matthew Hamilton"
date: "03/08/2020"
output: html_document
---

```{r include=F}
library(magrittr)
```

```{r child="../USER_PARAMS_RMDs/USER_PR_PUBS_PARAMS.Rmd", echo=FALSE}
```
```{r include=F}
replace_nbrs_tb <- read.csv("../Data/replace_nbrs_tb.csv") 
replace_nbrs_tb <- replace_nbrs_tb %>% dplyr::mutate(dplyr::across(names(replace_nbrs_tb),as.character))
peer_revd_tb_spine <- make_peer_revd_tb_spine(scholar_id_1L_chr = scholar_id_1L_chr,
exclude_ids_chr = exclude_ids_chr,
replace_nbrs_tb = replace_nbrs_tb,                        
sanitise_fn = sanitise_peer_revd_tb)

```
```{r include=F}
if(file.exists("../Data/accepted_tb.csv")){
  accepted_tb <- read.csv("../Data/accepted_tb.csv") 
accepted_tb <- accepted_tb %>% dplyr::mutate(dplyr::across(names(accepted_tb)[!names(accepted_tb) %in% c("Year","Citations","In_Press_Lgl")],as.character))
}else{
  accepted_tb <- NULL
}

peer_rvd_pubs_tbl <- make_peer_rvd_pubs_tbl(peer_revd_tb_spine,
                               accepted_tb = accepted_tb)
```
