---
name: Matthew
surname: Hamilton
aboutme: "I'm an economist who works to improve the policies and service systems that impact the mental health of young people. I principally do this by developing and validating reproducible and generalisable mental health simulation models."
position: "Health economist"
address: "Orygen"
phone: +61 413 976 905
www: orcid.org/0000-0001-7407-9194
email: "Matthew.Hamilton@Orygen.Org.Au"
github: matthewphamilton
linkedin: matthewhamiltonprofile
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
remove_commmas <- function(x){
  purrr::map_chr(x, ~ stringr::str_replace_all(.x,"\"",""))
}
get_fn_auts_1L_chr <- function(package_nm_1L_chr){ # Move to ready4show
  aut_chr <-  utils::packageDescription(package_nm_1L_chr,fields="Author") %>% strsplit("\n") %>% purrr::flatten_chr()
aut_chr <- aut_chr[aut_chr %>% stringr::str_detect("\\[aut")]
aut_1L_chr <- stringr::word(aut_chr,1,sep = "\\[aut") %>% trimws() %>% knitr::combine_words()
return(aut_1L_chr)
}
get_fn_remote_1L_chr <- function(package_nm_1L_chr){
  if(utils::packageDescription(package_nm_1L_chr,fields="RemoteHost") == "api.github.com"){
    remote_1L_chr <- paste0("https://github.com/",
                            utils::packageDescription(package_nm_1L_chr,fields="GithubUsername"),
                            "/",
                            utils::packageDescription(package_nm_1L_chr,fields="GithubRepo"))
  }else{
    remote_1L_chr <- NA_character_
  }
  return(remote_1L_chr)
}
```

```{r include=F}
# cits_tb <-rorcid::works(rorcid::as.orcid("0000-0001-7407-9194"))
# cits_tb %>% dplyr::select(title.title.value,`publication-date.year.value`,`journal-title.value`) %>% kableExtra::kable()
accepted_tb <- tibble::tibble(Title = c("Identification and Management of Psoriasis Associated Co-MorbidiTy: The IMPACT Research Programme"),
                              Author = c("L Cordingley, PA Nelson, L Davies, D Ashcroft, C Bundy, C Chew-Graham, A Chisholm, J Elvidge, M Hamilton,..."#" R Hilton, K Kane, C Keyworth, A Littlewood, K Lovell, M Lunt, H McAteer, D Ntais, R Parisi, C Pearce, M Rutter, D Symmons, H Young  & CEM Griffiths"
                                         ),
                              Journal = c("Programme Grants Appl Res"),
                              Year = 2020,
                              Citations = 0,
                              In_Press_Lgl = T)
published_tb <- scholar::get_publications("t1ZHrCoAAAAJ") %>%
  tibble::as_tibble() %>%
  dplyr::filter(!pubid %in% c("IjCSPb-OGe4C","0EnyYjriUFMC","kNdYIx-mwKoC","KlAtU1dfN6UC","3fE2CSJIrl8C","5nxA0vEk-isC","2osOgNQ5qMEC","Y0pCki6q_DkC")) %>%
  dplyr::arrange(dplyr::desc(year)) %>%
  dplyr::select(title,author,journal,year,cites) %>%
  dplyr::rename(Title = title, Author = author, Journal = journal, Year = year, Citations = cites) %>%
  dplyr::filter(Title != "Developing a youth suicide prevention strategy for Tasmania: A review of the literature") %>%
  dplyr::mutate(Author = purrr::map_chr(Author, ~ stringr::str_replace_all(.x,"RICKWOOD","Rickwood")))
pr_tb <- dplyr::bind_rows(accepted_tb,published_tb %>%
                            dplyr::mutate(In_Press_Lgl = F))
```

```{r include=F}
non_pr_tb <- read.csv("../Non_PR_Pubs.csv") %>%
  dplyr::mutate_all(remove_commmas)
```

```{r include=F}
presentations_tb <- read.csv("../Presentations.csv") %>%
  dplyr::mutate_all(remove_commmas)
```

```{r include=F}
grants_tb <- read.csv("../Grants.csv")
```

```{r include=F}
jobs_tb <- read.csv("../jobs.csv") %>%
  dplyr::mutate_all(remove_commmas)
quals_tb <- read.csv("../quals.csv") %>%
  dplyr::mutate_all(remove_commmas)
teaching_tb <- read.csv("../teaching.csv") %>%
  dplyr::mutate_all(remove_commmas)
```

```{r }
libs_tb <- tibble::tibble(Name = c(
  #"ready4show",
  #"ready4class",#"ready4sim","ready4space",
  #"ready4use",
  "ready4fun"),
               Type = c(#rep("App",2),rep("Model and context",2),
                 rep("SDK",1)),
  Language = "R") %>%
  dplyr::mutate(Description = purrr::map_chr(.$Name,
                                             ~ utils::packageDescription(.x, 
                                                                             fields = "Description")),
                Title = purrr::map_chr(.$Name,
                                        ~ packageDescription(.x, fields = "Title")),
                Version = purrr::map_chr(.$Name,
                                        ~ packageDescription(.x, fields = "Version")),
                Author = purrr::map_chr(.$Name,
                                        ~ get_fn_auts_1L_chr(.x)),
                Repository = purrr::map_chr(.$Name,
                                        ~ get_fn_remote_1L_chr(.x)),
                Date = purrr::map_chr(.$Name,
                                      ~ packageDate(.x) %>% format.Date("%d %B %Y"))
) %>%
  dplyr::mutate(Imports = purrr::map2_chr(.$Name,
                                          .$Type,
                                          ~ ifelse(.y=="App",
                                                   paste0(c("shiny",
                                                            paste0(ifelse(.x == "Springtides","springtides","s2lsd"),
                                                                   " (>= ",
                                                                   utils::packageDescription(ifelse(.x == "Springtides","springtides","s2lsd"), fields = "Version"),
                                                                   ")")
                                                          ) %>% sort(), 
                                                          sep=", ", 
                                                          collapse=""
                                                          ) %>%
                                                     stringr::str_sub(end=-2),
                                                   ifelse(.x == "ready4show",
                                                          c("bookdown,kableExtra,knitr,rmarkdown,rticles,shiny",
                                                            utils::packageDescription("ready4plot", 
                                                                             fields = "Imports") %>%
                                                              strsplit(", ") %>%
                                                              purrr::pluck(1)) %>% sort() %>%
                                                            paste0(sep=", ", collapse=""),
                                                   utils::packageDescription(.x, 
                                                                             fields = "Imports") %>% sort()))
                                          )

                )

 


```

# EDUCATION & QUALIFICATIONS

```{r quals}
quals_tb %>% 
  vitae::detailed_entries(
    what = What,
    when = When,
    with = With,
    where = Where)
```   

# EMPLOYMENT & APPOINTMENTS
```{r jobs}
jobs_tb %>% 
  vitae::detailed_entries(
    what = Title,#Employer,
    when = When,
    with = Employer,#Title,
    where = Where)
```

# PEER-REVIEWED PUBLICATIONS
```{r pr}
pr_tb %>% 
  #dplyr::mutate(New_Cites = as.character(Citations)) %>%
  dplyr::mutate(New_Cites = dplyr::case_when(In_Press_Lgl  ~ "In Press",
                                             TRUE ~ paste0(as.character(Citations)," cites"))) %>%
  dplyr::mutate(Year_Cites = paste0(Year," - ",New_Cites)) %>%
  vitae::detailed_entries(
    what = Author,#Title,
    when = Year_Cites,
    with = Title,#Author,
    where = Journal,
    .protect = TRUE)
```
\pagebreak
# NON-PEER-REVIEWED PUBLICATIONS
```{r nonpr}
non_pr_tb %>% 
  vitae::detailed_entries(
    what = Author,#Title,
    when = Year,
    with = Title,#Author,
    where = Publisher,
    .protect = TRUE)
```

# Code Libraries
```{r software}
libs_tb %>% 
  dplyr::mutate(Name_ver_title = paste0(Name,
                                        "(v",
                                        Version,
                                        ") - ",
                                        Title)) %>%
  vitae::detailed_entries(
    what = Author,
    when = Date,
    with = Name_ver_title,
    where = Repository,
    #why = Description,
    .protect = TRUE)
##
## NEED TO ADD APPS & DATASETS
```  

# Presentations
```{r presentaitons}
presentations_tb %>% 
  dplyr::mutate(Year_Format = paste0(Format," - ",Year)) %>%
  vitae::detailed_entries(
    what = Author...Presenter,
    when = Year_Format,
    with = Title,#Author,
    where = Host...Event,#Publisher,
    .protect = TRUE)
```
\pagebreak
# Grants
```{r grants}
grants_tb %>% 
    dplyr::mutate(Funder_Amt = paste0(Funder," - ",Amount)) %>%
  vitae::detailed_entries(
    what = Role,
    when = Year,
    with = Title,#Author,
    where = Funder_Amt,#Publisher,
    .protect = TRUE)
```

# Teaching
```{r teaching}
teaching_tb %>% 
      dplyr::mutate(Role_Inst = paste0(Role,", ",Institution)) %>%
  vitae::detailed_entries(
    what = Role_Inst,
    when = Year,
    with = Course,#Author,
    where = Location,#Role
    .protect = TRUE)
```   





