---
title: "CV_Body"
author: "Matthew Hamilton"
date: "03/08/2020"
output: html_document
---


```{r child="PR_Pubs_Body.Rmd", echo=FALSE}
```


```{r include=F}
non_pr_tb <- read.csv("../Data/Non_PR_Pubs.csv") %>%
  dplyr::mutate_all(remove_commmas)
```

```{r include=F}
presentations_tb <- read.csv("../Data/Presentations.csv") %>%
  dplyr::mutate_all(remove_commmas)
```

```{r include=F}
grants_tb <- read.csv("../Data/Grants.csv")
```

```{r include=F}
jobs_tb <- read.csv("../Data/Jobs.csv") %>%
  dplyr::mutate_all(remove_commmas)
quals_tb <- read.csv("../Data/Quals.csv") %>%
  dplyr::mutate_all(remove_commmas)
teaching_tb <- read.csv("../Data/Teaching.csv") %>%
  dplyr::mutate_all(remove_commmas)
```

```{r }
libs_tb <- tibble::tibble(Name = c(
  #"ready4show",
  #"ready4class",#"ready4sim","ready4space",
  #"ready4use",
  "ready4fun"),
               Type = c(#rep("App",2),rep("Model and context",2),
                 rep("SDK",1)),
  Language = "R") %>%
  dplyr::mutate(Description = purrr::map_chr(.$Name,
                                             ~ utils::packageDescription(.x, 
                                                                             fields = "Description")),
                Title = purrr::map_chr(.$Name,
                                        ~ packageDescription(.x, fields = "Title")),
                Version = purrr::map_chr(.$Name,
                                        ~ packageDescription(.x, fields = "Version")),
                Author = purrr::map_chr(.$Name,
                                        ~ get_fn_auts_1L_chr(.x)),
                Repository = purrr::map_chr(.$Name,
                                        ~ get_fn_remote_1L_chr(.x)),
                Date = purrr::map_chr(.$Name,
                                      ~ packageDate(.x) %>% format.Date("%d %B %Y"))
) %>%
  dplyr::mutate(Imports = purrr::map2_chr(.$Name,
                                          .$Type,
                                          ~ ifelse(.y=="App",
                                                   paste0(c("shiny",
                                                            paste0(ifelse(.x == "Springtides","springtides","s2lsd"),
                                                                   " (>= ",
                                                                   utils::packageDescription(ifelse(.x == "Springtides","springtides","s2lsd"), fields = "Version"),
                                                                   ")")
                                                          ) %>% sort(), 
                                                          sep=", ", 
                                                          collapse=""
                                                          ) %>%
                                                     stringr::str_sub(end=-2),
                                                   ifelse(.x == "ready4show",
                                                          c("bookdown,kableExtra,knitr,rmarkdown,rticles,shiny",
                                                            utils::packageDescription("ready4plot", 
                                                                             fields = "Imports") %>%
                                                              strsplit(", ") %>%
                                                              purrr::pluck(1)) %>% sort() %>%
                                                            paste0(sep=", ", collapse=""),
                                                   utils::packageDescription(.x, 
                                                                             fields = "Imports") %>% sort()))
                                          )

                )

 


```

# Qualifications

```{r quals}
quals_tb %>% 
  vitae::detailed_entries(
    what = What,
    when = When,
    with = With,
    where = Where)
```   

# Employment and Appointments
```{r jobs}
jobs_tb %>% 
  vitae::detailed_entries(
    what = Title,#Employer,
    when = When,
    with = Employer,#Title,
    where = Where)
```

# Peer-reviewed publications
```{r pr}
pr_tb %>% 
  #dplyr::mutate(New_Cites = as.character(Citations)) %>%
  dplyr::mutate(New_Cites = dplyr::case_when(In_Press_Lgl  ~ "In Press",
                                             TRUE ~ paste0(as.character(Citations)," cites"))) %>%
  dplyr::mutate(Year_Cites = paste0(Year," - ",New_Cites)) %>%
  vitae::detailed_entries(
    what = Author,#Title,
    when = Year_Cites,
    with = Title,#Author,
    where = Journal,
    .protect = TRUE)
```
\pagebreak
# Non-peer-reviewed publications
```{r nonpr}
non_pr_tb %>% 
  vitae::detailed_entries(
    what = Author,#Title,
    when = Year,
    with = Title,#Author,
    where = Publisher,
    .protect = TRUE)
```
# Software

## R Code Libraries
```{r software}
libs_tb %>% 
  dplyr::mutate(Name_ver_title = paste0(Name,
                                        "(v",
                                        Version,
                                        ") - ",
                                        Title)) %>%
  vitae::detailed_entries(
    what = Author,
    when = Date,
    with = Name_ver_title,
    where = Repository,
    #why = Description,
    .protect = TRUE)
##
## NEED TO ADD APPS & DATASETS
```  

For the most up to date information about the software I develop visit:

https://readyforwhatsnext.github.io/readyforwhatsnext/

# Presentations
```{r presentaitons}
presentations_tb %>% 
  dplyr::mutate(Year_Format = paste0(Format," - ",Year)) %>%
  vitae::detailed_entries(
    what = Author...Presenter,
    when = Year_Format,
    with = Title,#Author,
    where = Host...Event,#Publisher,
    .protect = TRUE)
```
# Grants
```{r grants}
grants_tb %>% 
    dplyr::mutate(Funder_Amt = paste0(Funder," - ",Amount)) %>%
  vitae::detailed_entries(
    what = Role,
    when = Year,
    with = Title,#Author,
    where = Funder_Amt,#Publisher,
    .protect = TRUE)
```

# Teaching
```{r teaching}
teaching_tb %>% 
      dplyr::mutate(Role_Inst = paste0(Role,", ",Institution)) %>%
  vitae::detailed_entries(
    what = Role_Inst,
    when = Year,
    with = Course,#Author,
    where = Location,#Role
    .protect = TRUE)
```   





