---
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::markdowncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

```{r child="../Child_RMDs/Functions.Rmd", echo=FALSE}
```

```{r child="../Child_RMDs/PR_Pubs_Prep.Rmd", echo=FALSE}
```
```{r pr}
pr_tb %>% 
    dplyr::mutate(New_Cites = dplyr::case_when(In_Press_Lgl  ~ "In Press",
                                             TRUE ~ paste0(as.character(Citations)," cites"))) %>%
  dplyr::mutate(Year_Cites = paste0(Year," - ",New_Cites)) %>%
  dplyr::mutate(New_Number = dplyr::case_when(In_Press_Lgl  ~ "In Press",
                                             TRUE ~ Number)) %>%
  dplyr::mutate(Year_Number = New_Number %>% 
                  strsplit(", ") %>% 
                  purrr::map2_chr(Year,~ifelse(identical(.x,character(0)),
  as.character(.y),
  paste(ifelse(.x[1]=="",
               "",
               paste0(.x[1],",")),
  .y,
        ifelse(length(.x)<2,
               "",
               paste0(", ",.x[2]))
  )))) %>%
  vitae::detailed_entries(
    what = Title,
    when = Year_Cites,
    with = Author,
    where = Journal,
    .protect = TRUE)
```


